spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iprwc
    username: postgres
    password: Welkom#1!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

application:
  security:
    jwt:
      secret-key: LEaIeNm8jevIjOgp9BgTcEKwaHogpcB/Ujy8YJl4c5L8AkB5d7KNBk7EnoYnXbOcxBEHWGhwRfl7p8QLTMPJdA
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days